version: '3'

services:
  web:
    build: .
    command: bash -c "python ./leadmanager/manage.py makemigrations && python ./leadmanager/manage.py migrate && python ./leadmanager/manage.py runserver 0.0.0.0:8000"
    container_name: django-app
    volumes:
      - .:/django-app
    ports:
      - "8000:8000"